version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
    nodejs: "16"
  commands:
    - npm install
    - npm run dist
    - pip install -r requirements.txt
    - inv preview
    - mkdir _readthedocs/
    - mv output _readthedocs/html
