# Read the Docs configuration file

# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
    nodejs: "20"

  # https://docs.readthedocs.com/platform/latest/config-file/v2.html#build-commands
  commands:
    - npm clean-install
    - npm run dist
    - pip install -r requirements.txt
    - inv preview
    - mkdir _readthedocs/
    - mv output _readthedocs/html
