# https://docs.astral.sh/uv/guides/integration/github/
name: Build and HTML validate the Pelican site

on: push

jobs:
  deploy:
    name: Build and Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      # Installs Python specified in pyproject.toml
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          # Install a specific version of uv.
          version: "0.8.22"
          # Cache project deps
          # https://docs.astral.sh/uv/guides/integration/github/#caching
          enable-cache: true

      - name: Build static assets
        run: |
          npm clean-install
          npm run dist

      - name: Install project deps
        run: uv sync --locked --all-extras --dev

      - name: Run linting
        run: uv run pre-commit run --all-files

      - name: Build site with Pelican
        id: run-pelican
        run: |
          uv run inv preview

      - name: Run Validator
        run: uvx html5validator --config htmlvalidator.yaml
